name: Version Alias
description: Automatically update version aliases for GitHub Actions repositories.
inputs:
  match-tag:
    description: The tag name to check
    required: false
    default: ''
  alias-minor:
    description: Enable creation of minor version aliases
    required: false
    default: 'true'
  alias-major:
    description: Enable creation of major version aliases
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Dump github context
      if: env.DEBUG_MODE == 1
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Node, npm versions, and install
      run: |
        node --version
        npm --version
        npm install
        rm package-lock.json
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Sync versions
      id: sync_versions
      run: node ${{ env.DEBUG_MODE == '1' && '--inspect-brk=9229' || '' }} ${{ github.action_path }}/index.js
      shell: bash
      env:
        MATCH_TAG: ${{ inputs.match-tag }}
        ALIAS_MINOR: ${{ inputs.alias-minor }}
        ALIAS_MAJOR: ${{ inputs.alias-major }}
